### ISSUE TITLE
Update the list of usernames to block

### ISSUE THREAD

**Issue by sandrasgg** [infinite-wait/blockout2024#4]
**Help needed**

The usernames list (`instagram_usernames.txt`) needs to be updated as the number of accounts to block keeps increasing.

**Comment by jzhang319** [comment]
I am not 100% clear on what you want to do. How do you want the txt file to be updated ? I assume you want to add usernames into the txt file automatically from somewhere but who exactly is it going decide what usernames to add inside the list.

**Comment by molinto** [comment]
Helpful lists:
https://blockout2024.org/
https://docs.google.com/spreadsheets/u/2/d/1md2THcnGgTXYqXd3fDK2DAhR2g6xoEtkyg-RFMcckG8/htmlview

**Comment by sandrasgg** [comment]
Hey @jzhang319! Thanks for the interest! The main goal of this task is to keep the list of usernames updated, as it is currently incomplete. Having it being automatically updated would be awesome but may still require some manual steps as this script is not running on any server recurrently. Another issue is that I'm not aware of there being a complete unified list anywhere, as all I'm finding are separate sources of usernames that complement each other. 

All of these reasons are the cause of me creating this request for help but I don't think we need to design a complex way to keep it updated at this point, I think that one that is practical enough is fine (manually adding them is not ideal but still very welcome). The two sources that @molinto mentions above (big thanks to you for attaching them btw! 😍) are perfect to have a more complete list at the moment 😃
