### ISSUE TITLE
2FA not allowing me to connect

### ISSUE THREAD

**Issue by ryaneford** [infinite-wait/blockout2024#5]
As title says.

**Comment by infinite-wait** [comment]
Hi @ryaneford! Could you provide the traceback of the error? Thanks

**Comment by infinite-wait** [comment]
I saw that @loosiegoosey has been working on this, feel free to open a PR and contribute to the project :)

**Comment by loosiegoosey** [comment]
I’m traveling this weekend and will try to contribute to your project once I return. Y’all did Great work so far in getting this to work. Also I did want to note that I received an in-app message saying automated actions were detected. Dunno if anyone else got that.

**Comment by loosiegoosey** [comment]
> contribute to the project

I'd love to join and contribute. I believe I solved the 2fa bug in my fork (Instagram.py file). I ran into the sane issue when I first started.

**Comment by loosiegoosey** [comment]
IDK how exactly pull requests work with GitHub but I think I managed to finally do it correctly this time. I pushed proposed changes from a new fork to fix this bug
