### ISSUE TITLE
Enhancement: Retrieve and Compare Blocked User List from Instagram Using Instagrapi

### ISSUE THREAD

**Issue by loosiegoosey** [infinite-wait/blockout2024#7]
As the username block list grows in length, it might be more efficient to get a list of blocked users from Instagram to compare currently blocked usernames with the Instagram username list. I looked at the instagrapi documentation a bit and didn't see anything like get_blocked_users, so I'm not entirely sure if what I'm proposing is possible.

**Comment by infinite-wait** [comment]
Thanks for the suggestion @loosiegoosey, I think it makes a lot of sense. I'll work on this asap 👌

**Comment by molinto** [comment]
Perhaps a visit to the users page:
https://www.instagram.com/accounts/blocked_accounts/

**Comment by loosiegoosey** [comment]
@molinto good idea. perhaps parse the HTML and extract the blocked usernames using a library like beautifulsoup4 to scrape the webpage?

**Comment by infinite-wait** [comment]
It's a good idea, I believe we'll have to deal with some kind of pagination though. Having +300 blocked accounts already takes some time to load the full list.

**Comment by infinite-wait** [comment]
After researching this, it seems that scrapping Instagram would not be the best solution, as Instagram tracks all scrapping activity and may lead to banning. Instead, I'd go for a more custom solution by manually keeping track of all blocked users in the repository cache dir after the first execution.

**Comment by infinite-wait** [comment]
Closing this issue after applying the last suggestion. Keeping it this way until instagrapi allows to retrieve the list of an account's blocked users.
